### ISSUE TITLE
[node:973] UnhandledPromiseRejectionWarning: Slack API error 'invalid_blocks' at postMessageWithPayload in slack.js

### ISSUE THREAD

**Issue by nick-bratton** [nick-bratton/susi#12]
```
(node:973) UnhandledPromiseRejectionWarning: Error: An API error occurred: invalid_blocks
    at Object.platformErrorFromResult (foo/node_modules/@slack/web-api/dist/errors.js:50:33)
    at WebClient.apiCall (foo/node_modules/@slack/web-api/dist/WebClient.js:382:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async postMessageWithPayload (foo/services/slack.js:78:3)
(node:973) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

```
(node:973) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nick-bratton** [comment]
Fixed but simply by throwing an error. No retries as of now. Still closing issue.

See commit 6642963
